name: Test package

on:
  push:
    # The CI is executed on every push on every branch
    branches:
      - main
  pull_request:
    # The CI is executed on every pull request to the main branch
    branches:
      - main

jobs:
  check-code:
 
    runs-on: ubuntu-22.04

    container: ghcr.io/scientificcomputing/fenics:2023-01-16

    steps:
      # This action sets the current path to the root of your github repo
      - uses: actions/checkout@v3

      - name: "Install code"
        run: python3 -m pip install .[test]

        #      - name: Flake8 code
        #        run: python -m flake8
        #
        #      - name: Mypy check
        #        run: python -m mypy

  test-code:
    # This code depends on the result of check-code
    needs: check-code
    runs-on: ubuntu-22.04
    container: ghcr.io/scientificcomputing/fenics:2023-01-16
    
    steps:

      - uses: actions/checkout@v3

      - name: "Install ffian"
        run: python3 -m pip install .[test]

      - name: Run tests
        run: |
          python -m pytest
